/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/colors': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Retrieve all colors
     * @description Returns the full list of colors stored in the database.
     */
    get: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description A list of colors */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['Color'][]
          }
        }
        /** @description Server error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
      }
    }
    put?: never
    /**
     * Create a new color
     * @description Adds a new color to the database. Both `name` and `hex` are required. Returns 409 if a color with the same name already exists.
     */
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody: {
        content: {
          'application/json': components['schemas']['Color']
        }
      }
      responses: {
        /** @description Color created successfully */
        201: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['Color']
          }
        }
        /** @description Invalid input data (e.g., empty name, invalid hex format) */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['Error']
          }
        }
        /** @description A color with that name already exists */
        409: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Too many requests */
        429: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Server error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/colors/{name}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Retrieve a single color by name
     * @description Looks up a color by its name (case-sensitive).
     */
    get: {
      parameters: {
        query?: never
        header?: never
        path: {
          /**
           * @description The color name to look up
           * @example Red
           */
          name: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description The matching color */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['Color']
          }
        }
        /** @description Invalid color name format */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['Error']
          }
        }
        /** @description Color not found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Server error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
      }
    }
    /**
     * Update an existing color
     * @description Updates the hex value (and optionally the name) of an existing color. The color is identified by its current name in the URL path.
     */
    put: {
      parameters: {
        query?: never
        header?: never
        path: {
          /**
           * @description Current name of the color to update
           * @example Turquoise
           */
          name: string
        }
        cookie?: never
      }
      requestBody: {
        content: {
          'application/json': components['schemas']['UpdateColor']
        }
      }
      responses: {
        /** @description Color updated successfully */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['Color']
          }
        }
        /** @description Invalid input data (e.g., empty name, invalid hex format) */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['Error']
          }
        }
        /** @description Color not found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description A color with the new name already exists */
        409: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Server error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
      }
    }
    post?: never
    /**
     * Delete a color by name
     * @description Permanently removes the color with the given name from the database.
     */
    delete: {
      parameters: {
        query?: never
        header?: never
        path: {
          /**
           * @description Name of the color to delete
           * @example Yellow
           */
          name: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Color deleted successfully */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              /** @example Color "Yellow" deleted successfully */
              message?: string
            }
          }
        }
        /** @description Invalid color name format */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['Error']
          }
        }
        /** @description Color not found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Server error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
      }
    }
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    Color: {
      /**
       * @description Human-readable color name
       * @example Turquoise
       */
      name: string
      /**
       * @description Hex color code including the leading
       * @example #1abc9c
       */
      hex: string
    }
    Error: {
      /** @description Error message */
      error?: string
    }
    UpdateColor:
      | {
          /**
           * @description New name for the color
           * @example Turquoise
           */
          name?: string
          /**
           * @description New hex code for the color
           * @example #1abc9c
           */
          hex?: string
        }
      | unknown
      | unknown
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export type operations = Record<string, never>
