# MegaLinter configuration file
# See all available variables at https://oxsecurity.github.io/megalinter/configuration/
---
# ------------------------------------------------------------------------------
# SCOPE
# ------------------------------------------------------------------------------
# Only analyze specific folders
FILTER_REGEX_INCLUDE: "(src|server)/.*"
FILTER_REGEX_EXCLUDE: "(node_modules|megalinter-reports)/.*"

# Disable linters that conflict with existing setups or are too noisy
DISABLE_LINTERS:
  - REPOSITORY_DEVSKIM
  - REPOSITORY_TRUFFLEHOG
  - REPOSITORY_KINGFISHER
  - REPOSITORY_GRYPE
  - REPOSITORY_KICS
  - REPOSITORY_TRIVY
  - COPYPASTE_JSCPD
  - JSON_V8R
  - DOCKERFILE_HADOLINT
  - JAVASCRIPT_ES
  - TYPESCRIPT_ES
  - TSX_ESLINT

SPELL_CSPELL_FILTER_REGEX_EXCLUDE: "(src/locales/.*)"
SPELL_LYCHEE_FILTER_REGEX_EXCLUDE: '(server/package.*\.json)'
