# MegaLinter configuration file
# See all available variables at https://oxsecurity.github.io/megalinter/configuration/
---

# ------------------------------------------------------------------------------
# SCOPE
# ------------------------------------------------------------------------------
# Only analyze specific folders
FILTER_REGEX_INCLUDE: '(src|server)/.*'
