# SonarCloud Configuration
sonar.organization=jpourdanis
sonar.projectKey=jpourdanis_test-automation-best-practices
sonar.host.url=https://sonarcloud.io

# Path to the source directories
sonar.sources=src,server
# Path to the test directories
sonar.tests=src,server,e2e

# Source and Test inclusions/exclusions
# Exclude tests from sonar.sources
sonar.exclusions=**/*.test.js,**/*.test.tsx,**/*.test.ts,**/*.spec.ts,**/*.spec.js,node_modules/**,build/**,dist/**,allure-results/**,coverage/**,reports/**,.nyc_output/**
# Inclusions for sonar.tests
sonar.test.inclusions=src/**/*.test.tsx,src/**/*.test.ts,server/**/*.test.js,server/**/*.int.test.js,e2e/**/*.spec.ts,e2e/**/*.spec.js,e2e/**/*.feature

# Coverage configuration
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Reporting and Encoding
sonar.sourceEncoding=UTF-8

# Specific file extensions
sonar.lang.patterns.ts=**/*.ts,**/*.tsx
sonar.lang.patterns.js=**/*.js,**/*.jsx
