export { ColorSchema, CreateColorSchema, UpdateColorSchema, STRICT_NAME_REGEX, STRICT_NAME_MSG } from './schemas/color'
export type { Color } from './schemas/color'
export { apiClient, createApiClient } from './api/client'
export type { ApiClientOptions, ColorBody, UpdateColorBody } from './api/client'
export type { paths, components } from './api/openapi.d.ts'
export { enTranslations, esTranslations, elTranslations } from './locales'
export type { Translations } from './locales'
